### ISSUE TITLE
Error: Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/trading-bot#1]
```sh
Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (/usr/src/app/node_modules/web3-eth-abi/src/index.js:226:15)
    at Contract._decodeMethodReturn (/usr/src/app/node_modules/web3-eth-contract/src/index.js:465:22)
    at Method.outputFormatter (/usr/src/app/node_modules/web3-eth-contract/src/index.js:818:46)
    at Method.formatOutput (/usr/src/app/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (/usr/src/app/node_modules/web3-core-method/src/index.js:473:33)
    at /usr/src/app/node_modules/web3-core-requestmanager/src/index.js:147:9
    at XMLHttpRequest.request.onreadystatechange (/usr/src/app/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/src/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/usr/src/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/usr/src/app/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by JulianWe** [comment]
Settings Mainnet RPC in .env file
