### ISSUE TITLE
 Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.7.0)

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/trading-bot#5]
```sh
Performing swap on kyber, expected profit:  62.346603979013935  USD$
Performing swapEtherToTokens on Kyber...
{ Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.7.0)
    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Contract.<anonymous> (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:427:36)
    at step (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at /usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:19:12)
    at Contract.<anonymous> (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:421:16)
    at kyberSwapEtherToToken (/usr/src/app/index.js:106:28)
    at checkPair (/usr/src/app/index.js:237:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason: 'sending a transaction requires a signer',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'sendTransaction' }

```

**Comment by JulianWe** [comment]
```sh
// ETHERS CONFIG
const provider = new ethers.providers.JsonRpcProvider(process.env.RPC_URL);
const wallet = new ethers.Wallet(process.env.PRIVATE_KEY);
const signer = wallet.connect(provider);
const kyber = new ethers.Contract(legos.kyber.network.address, legos.kyber.network.abi, signer);
```
