### ISSUE TITLE
Error: resolver or addr is not configured for ENS name (argument="name", value="500000000000000000", code=INVALID_ARGUMENT, version=contracts/5.7.0)

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/trading-bot#6]
```sh
{ Error: resolver or addr is not configured for ENS name (argument="name", value="500000000000000000", code=INVALID_ARGUMENT, version=contracts/5.7.0)
    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at /usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:110:32
    at step (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason: 'resolver or addr is not configured for ENS name',
  code: 'INVALID_ARGUMENT',
  argument: 'name',
  value: '500000000000000000' }

```

**Comment by JulianWe** [comment]
```sh 
 let result = await kyber.swapEtherToToken(swapEtherToToken, token)
 let result = await kyber.swapEtherToToken(token, swapEtherToToken)
```

Just swap variabels
