### ISSUE TITLE
Error: cannot estimate gas; transaction may fail or may require manual gas limit

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/trading-bot#7]
```sh
{ Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x0f0d2BF29AAe4E6D8d646F967Df8c49B28Df05E5","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x05c602ac9c"},"to":"0x818E6FECD516Ecc3849DAf6845e3EC868087B755","data":"0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000","type":2,"accessList":null},"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":55,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x5c602ac9c\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x0f0d2bf29aae4e6d8d646f967df8c49b28df05e5\",\"to\":\"0x818e6fecd516ecc3849daf6845e3ec868087b755\",\"data\":\"0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000\"}],\"id\":55,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/5309f62fbf1f41eb97e16033efed3ca4"}}, tx={"data":"0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000","to":{},"from":"0x0f0d2BF29AAe4E6D8d646F967Df8c49B28Df05E5","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0x05c602ac9c"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)
    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /usr/src/app/node_modules/@ethersproject/abstract-signer/lib/index.js:365:47
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason:
   'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error:
   { Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x0f0d2BF29AAe4E6D8d646F967Df8c49B28Df05E5","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x05c602ac9c"},"to":"0x818E6FECD516Ecc3849DAf6845e3EC868087B755","data":"0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000","type":2,"accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":55,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x5c602ac9c\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x0f0d2bf29aae4e6d8d646f967df8c49b28df05e5\",\"to\":\"0x818e6fecd516ecc3849daf6845e3ec868087b755\",\"data\":\"0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000\"}],\"id\":55,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/5309f62fbf1f41eb97e16033efed3ca4"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
       at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
       at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
       at checkError (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:122:20)
       at JsonRpcProvider.<anonymous> (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)
       at step (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
       at Object.throw (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
       at rejected (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     reason: 'execution reverted',
     code: 'UNPREDICTABLE_GAS_LIMIT',
     method: 'estimateGas',
     transaction:
      { from: '0x0f0d2BF29AAe4E6D8d646F967Df8c49B28Df05E5',
        maxPriorityFeePerGas: [BigNumber],
        maxFeePerGas: [BigNumber],
        to: '0x818E6FECD516Ecc3849DAf6845e3EC868087B755',
        data:
         '0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000',
        type: 2,
        accessList: null },
     error:
      { Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":55,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x5c602ac9c\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x0f0d2bf29aae4e6d8d646f967df8c49b28df05e5\",\"to\":\"0x818e6fecd516ecc3849daf6845e3ec868087b755\",\"data\":\"0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000\"}],\"id\":55,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://mainnet.infura.io/v3/5309f62fbf1f41eb97e16033efed3ca4", code=SERVER_ERROR, version=web/5.7.1)
          at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
          at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
          at /usr/src/app/node_modules/@ethersproject/web/lib/index.js:313:32
          at step (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:33:23)
          at Object.next (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:14:53)
          at fulfilled (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:5:58)
          at process._tickCallback (internal/process/next_tick.js:68:7)
        reason: 'processing response error',
        code: 'SERVER_ERROR',
        body:
         '{"jsonrpc":"2.0","id":55,"error":{"code":-32000,"message":"execution reverted"}}',
        error: [Error],
        requestBody:
         '{"method":"eth_estimateGas","params":[{"type":"0x2","maxFeePerGas":"0x5c602ac9c","maxPriorityFeePerGas":"0x59682f00","from":"0x0f0d2bf29aae4e6d8d646f967df8c49b28df05e5","to":"0x818e6fecd516ecc3849daf6845e3ec868087b755","data":"0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000"}],"id":55,"jsonrpc":"2.0"}',
        requestMethod: 'POST',
        url:
         'https://mainnet.infura.io/v3/5309f62fbf1f41eb97e16033efed3ca4' } },
  tx:
   { data:
      '0x7a2a04560000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c00000000000000000000000000000000000000000000000006f05b59d3b20000',
     to: Promise { '0x818E6FECD516Ecc3849DAf6845e3EC868087B755' },
     from: '0x0f0d2BF29AAe4E6D8d646F967Df8c49B28Df05E5',
     type: 2,
     maxFeePerGas: BigNumber { _hex: '0x05c602ac9c', _isBigNumber: true },
     maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
     nonce: Promise { 152 },
     gasLimit: Promise { <rejected> [Circular] },
     chainId: Promise { 1 } } }

```

**Comment by JulianWe** [comment]
Maybe this one https://ethereum.stackexchange.com/questions/150579/periodic-failure-when-attempting-to-create-gnosis-safe-via-safe-global-protocol/150771#150771

**Comment by JulianWe** [comment]
adding  ` gasLimit: 250000` to contract call
```
  let result = await kyber.swapTokenToEther(outputTokenAddress, ETH_AMOUNT, {
    gasLimit: 250000
  });
```
